config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
               registrations: "users/registrations",
               sessions:      "users/sessions",
               passwords:     "users/passwords",
               confirmations: "users/confirmations"
             }
  devise_scope :user do
    get "signup",  to: "users/registrations#new"
    get "signin",  to: "users/sessions#new"
    delete "signout", to: "users/sessions#destroy"
  end
  root "products#index"
  get "about", to: "products#about"
  post "products/add_to_cart/:id", to: "products#add_to_cart", as: "add_to_cart"
  delete "products/remove_from_cart/:id", to: "products#remove_from_cart", as: "remove_from_cart"
  get "orders/new", to: "orders#new", as: "checkout"
  post "orders/update_taxes/:province_id", to: "orders#update_taxes", as: "update_taxes"

  resources :products
  resources :categories
  resources :users
  resources :orders
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
# Xote e-commerce
# Paloma Brandao

class Product < ApplicationRecord
  belongs_to :category
  has_many :stocks, dependent: :destroy
  has_many :orders, through: :carts
  has_many :carts, dependent: :destroy
  has_one_attached :image

  validates :name, presence: true, length: { within: 3..60 }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :alcohol, inclusion: [true, false]

  scope :new_products, -> { where("created_at >= ?", 3.days.ago) }
  scope :updated, -> { where("updated_at >= ?", 3.days.ago) }
  scope :sale, -> { where(on_sale: true) }
  scope :search_products, lambda { |search_words, category_id|
                            products = if category_id.present?
                                         where("category_id = ?", category_id)
                                       else
                                         all
                                       end
                            if search_words
                              products = products.where("name LIKE ? OR description LIKE ?",
                                                        "%#{sanitize_sql_like(search_words)}%",
                                                        "%#{sanitize_sql_like(search_words)}%")
                            end
                            products
                          }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :initialize_session
  before_action :increment_visit_count
  before_action :load_cart

  def index
    @products = if params[:search] || params[:category_id]
                  Product.search_products(params[:search], params[:category_id])
                else
                  Product.includes(:category).all
                end
  end

  def show
    @product = Product.find(params[:id])
  end

  def about; end

  def add_to_cart
    id = params[:id].to_i
    session[:cart] << id unless session[:cart].include?(id)
    redirect_to root_path
  end

  def remove_from_cart
    id = params[:id].to_i
    session[:cart].delete(id)
    redirect_to root_path
  end

  private

  def initialize_session
    session[:visit_count] ||= 0
    session[:cart] ||= []
  end

  def increment_visit_count
    session[:visit_count] += 1
    @visit_count = session[:visit_count]
  end

  def load_cart
    @cart = Product.find(session[:cart])
  end

  def product_params
    params.require(:product).permit(:id, :name, :description, :on_sale, :search, :category_id)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_list.html.erb
<p>
  <% if product.image.attached? %>
    <%= image_tag url_for(product.image.variant(resize_to_limit: [nil,
                                                                     100]).processed) %>
  <% end %>
  ID: <%= product.id %><br>
  Price: <%= number_to_currency product.price %><br>
  Category: <%= product.category.name %>
  <% if cart.include?(product) %>
    <p>Product is in your cart.</p>
  <% else %>
    <p><%= link_to "add to cart", add_to_cart_path(product.id), method: :post %></p>
  <% end %>
</p>

app/views/products/about.html.erb
<div class="about">
  <h1>About Us</h1>

</div>

app/views/products/index.html.erb
<% content_for(:sidebar) do %>
  <%= render :partial => "layouts/sidebar" %>
<% end %>

<div class="d-flex flex-column justify-content-center col-sm-9 col-md-10 main">
  <div class="row px-5 py-2 center">
    <h1>Products</h1>
  </div>
  <div class="row col-sm-6 col-md-6 ms-auto">
    <details>
      <summary>Shopping Cart</summary>
      <% if @cart.empty? %>
        <p>No items in cart</p>
      <% else %>
        <ul>
          <% @cart.each do |product| %>
            <li>
              <%= product.name %> - <%= link_to "Remove from cart", remove_from_cart_path(product), method: :delete %>
                <i class="bi bi-x-circle-fill remove"></i>
            </li>
          <% end %>
          <%= form_with url: :checkout, method: :get do |f| %>
            <li><%= f.submit "Checkout", class: "btn btn-small btn-primary"%></li>
          <% end %>
        </ul>
      <% end %>
    </details>
  </div>
  <div class="row px-5">
    <p>You have visied this site <%= pluralize @visit_count, "time" %>.</p>
  </div>
  <% @products.each do |product| %>
    <div class="row px-5">
        Name: <%= link_to product.name, product_path(product) %>
      <%= render "list", product: product, cart: @cart %>
    </div>
  <% end %>
</div>

app/views/products/show.html.erb
<% content_for(:sidebar) do %>
  <%= render :partial => "layouts/sidebar" %>
<% end %>
<div class="d-flex flex-column justify-content-center col-md-7 offset-md-3 main">
  <h1><%= @product.name %></h1>

  <% if @product.image.attached? %>
    <%= image_tag url_for(@product.image.variant(resize_to_limit: [nil,
                                                                     300]).processed) %>
  <% end %>
  <ul>
    <li>
      Description: <%= @product.description %>
    </li>
    <li>
      Price: $<%= @product.price %>
    </li>
    <li>
      Category: <%= @product.category.name %>
    </li>

  </ul>
</div>