config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
               registrations: "users/registrations",
               sessions:      "users/sessions",
               passwords:     "users/passwords",
               confirmations: "users/confirmations"
             }
  devise_scope :user do
    get "signup",  to: "users/registrations#new"
    get "signin",  to: "users/sessions#new"
    delete "signout", to: "users/sessions#destroy"
  end
  root "products#index"
  get "about", to: "products#about"
  post "products/add_to_cart/:id", to: "products#add_to_cart", as: "add_to_cart"
  delete "products/remove_from_cart/:id", to: "products#remove_from_cart", as: "remove_from_cart"
  get "orders/new", to: "orders#new", as: "checkout"
  post "orders/update_taxes/:province_id", to: "orders#update_taxes", as: "update_taxes"

  resources :products
  resources :categories
  resources :users
  resources :orders
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
# Xote e-commerce
# Paloma Brandao

class Address < ApplicationRecord
  belongs_to :province
  belongs_to :user
  has_many :orders, dependent: :destroy

  validates :province, presence: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
# Xote e-commerce
# Paloma Brandao

class Cart < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :quantity, numericality: { greater_than: 0, only_integer: true }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :tax, numericality: { greater_than_or_equal_to: 0 }
end

app/models/category.rb
# Xote e-commerce
# Paloma Brandao

class Category < ApplicationRecord
  has_many :products, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/city.rb
# Xote e-commerce
# Paloma Brandao

class City < ApplicationRecord
  belongs_to :province
  has_many :addresses, dependent: :destroy

  validates :name, presence: true, length: { within: 2..50 }
end

app/models/order.rb
# Xote e-commerce
# Paloma Brandao

class Order < ApplicationRecord
  belongs_to :user
  belongs_to :address
  belongs_to :order_status
  has_many :products, through: :carts
  has_many :carts, dependent: :destroy

  accepts_nested_attributes_for :address, allow_destroy: true
  accepts_nested_attributes_for :carts, allow_destroy: true

  validates :user, presence: true
  validates :address, presence: true
end

app/models/order_status.rb
# Xote e-commerce
# Paloma Brandao

class OrderStatus < ApplicationRecord
  has_many :orders, dependent: :destroy

  validates :name, presence: true, length: { within: 3..20 }
end

app/models/product.rb
# Xote e-commerce
# Paloma Brandao

class Product < ApplicationRecord
  belongs_to :category
  has_many :stocks, dependent: :destroy
  has_many :orders, through: :carts
  has_many :carts, dependent: :destroy
  has_one_attached :image

  validates :name, presence: true, length: { within: 3..60 }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :alcohol, inclusion: [true, false]

  scope :new_products, -> { where("created_at >= ?", 3.days.ago) }
  scope :updated, -> { where("updated_at >= ?", 3.days.ago) }
  scope :sale, -> { where(on_sale: true) }
  scope :search_products, lambda { |search_words, category_id|
                            products = if category_id.present?
                                         where("category_id = ?", category_id)
                                       else
                                         all
                                       end
                            if search_words
                              products = products.where("name LIKE ? OR description LIKE ?",
                                                        "%#{sanitize_sql_like(search_words)}%",
                                                        "%#{sanitize_sql_like(search_words)}%")
                            end
                            products
                          }
end

app/models/province.rb
# Xote e-commerce
# Paloma Brandao

class Province < ApplicationRecord
  has_many :cities, dependent: :destroy

  validates :name, presence: true, length: { within: 3..25 }
  validates :gst, numericality: { greater_than_or_euqal_to: 0 }
  validates :pst, numericality: { greater_than_or_euqal_to: 0 }
  validates :hst, numericality: { greater_than_or_euqal_to: 0 }
end

app/models/stock.rb
# Xote e-commerce
# Paloma Brandao

class Stock < ApplicationRecord
  belongs_to :product

  validates :quantity, numericality: { greater_than_or_euqal_to: 0, only_integer: true }
  validates :made_on, presence: true
  validates :durable_life, numericality: { greater_than: 0, only_integer: true }
end

app/models/user.rb
# Xote e-commerce
# Paloma Brandao

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  accepts_nested_attributes_for :addresses, allow_destroy: true

  validates :first_name, presence: true, length: { within: 2..20 }
  validates :last_name, presence: true, length: { within: 2..50 }
  validates :email, presence: true
end

app/models/user_type.rb
class UserType < ApplicationRecord
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :new_order, only: [:new]

  def new
    session["cart"].each do |item|
      @order.carts.build(load_cart(item).attributes)
    end
    @order.tax = set_tax
  end

  def create
    @order = Order.new(order_params)

    if @order.save
      redirect_to root_path
    else
      render :new
    end
  end

  def update_taxes
    @order.address = Address.new(province_id: params[:province_id])
    @order.tax = set_tax
    render :new
  end

  private

  def new_order
    @order_total ||= 0
    @order ||= Order.new(user:         User.includes(:addresses).find(current_user.id),
                         order_status: OrderStatus.find_by(name: "New"))
    @order.address ||= @order.user&.addresses&.first
  end

  def set_tax
    if @order.address.province.hst.positive?
      @order.address.province.hst
    else
      @order.address.province.pst + @order.address.province.gst
    end
  end

  def load_cart(item)
    cart_item = Cart.new(quantity: 1, product: Product.find(item))
    cart_item.price = cart_item.product.price
    @order_total += cart_item.price
    cart_item
  end

  def order_params
    params.require(:order).permit(:id, :tax, :user_id, :order_status_id, :address_id,
                                  carts_attributes: %i[id product_id quantity price])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.includes(:addresses).find(params[:id])
    @addresses = Address.find_or_initialize_by(user_id: params[:id])
    @user[:email] = current_user.email
    @user.addresses.build(@addresses.attributes)
  end

  def show
    @user = User.includes(:addresses).find(params[:id])
  end

  def update
    @user = User.includes(:addresses).find(params[:id])

    if @user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:id, :first_name, :last_name, :birthday, :email,
                                 addresses_attributes: %i[id name line01 line02 postal_code
                                                          city user_id province_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_address.html.erb
<div class="row col-12">
  <p>Address type: <%= addr.name %></p>
  <p>Line 1: <%= addr.line01 %></p>
  <p>line 2: <%= addr.line02 %></p>
  <p>City: <%= addr.city %></p>
  <p>Province: <%= addr.province.abbreviation %></p>
  <p>Postal code: <%= addr.postal_code %></p>
</div>

app/views/layouts/_contactfields.html.erb
<%= form_with model: user do |f| %>
  <%= f.text_field :first_name, placeholder: "First name", :class => "form-control" %>
  <%= f.text_field :last_name, placeholder: "Last name", :class => "form-control" %>
  <%= f.text_field :email, placeholder: "Email", :class => "form-control", readonly: true %>

  <% user.addresses.each do |addr| %>
    <%= f.fields_for :addresses, addr do |af| %>
      <%= af.text_field :name, placeholder: "Kind of address", :class => "form-control" %>
      <%= af.text_field :line01, placeholder: "Line 1", :class => "form-control" %>
      <%= af.text_field :line02, placeholder: "line 2", :class => "form-control" %>
      <%= af.collection_select :province_id, Province.order(:name), :id, :name %>
      <%= af.text_field :city, :class => "form-control" %>
      <%= af.text_field :postal_code, placeholder: "Postal Code", :class => "form-control" %>
    <% end %>
  <% end %>
  <%= f.submit class: "btn btn-large btn-primary" %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <span><%= link_to "Mandyoka", root_path, class: "navbar-brand", id: "logo" %></span>
    <span class="beta">Beta</span>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <% if signed_in? %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          <% else %>
            <%= link_to "Sign in", signin_path, class: "nav-link" %>
          <% end %>

        </li>
        <li class="nav-item">
          <%= link_to "Admin", admin_root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Products", products_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Categories", categories_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Shopping Cart</a>
        </li>
      </ul>
      <%= form_tag(products_path, class: "d-flex", method: :get) do %>
        <%= select_tag "category_id", options_from_collection_for_select(@categories, "id", "name"), include_blank: "All categories", id: "category_id" %>
        <%= text_field_tag(:search, params[:search], class: "form-control me-2", placeholder: "Search") %>
        <%= submit_tag("Search", class: "btn btn-outline-success") %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="d-flex col-sm-3 col-md-2 sidebar">
  <ul>
    <li>Menu</li>
    <% @categories.each do |category| %>
      <li>
        <%= link_to category.name, category_path(category) %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Xote</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="app_body <%= controller_name %> <%= action_name%>">
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %> col-md-8  offset-md-2 main">
          <%= value %>
        </div>
      <% end %>
      <div class="d-flex flex-row">
        <%= yield :sidebar %>
        <%= yield %>
      </div>
    </div>
    <% debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<%if @user %>
  <% if @user.errors.any? %>
    <div id="error_explanation" class="col-md-12">
      <div class="alert alert-danger" role="alert">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
        <% @user.errors.each do |error| %>
        <li>* <%= error.attribute %> - <%= error.message %> </li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>